server:
  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: _HOST_
          port: 5432
          database: temporal
          user: _USER_
          password: _PASSWORD_
          # for a production deployment use this instead of `password` and/or `user`. The secret needs to be provisioned
          # beforehand e.g. with a sealed secret. Keys for the user and the password need to be stored in the same secret.
          # you can specify the secret name and the keys in the following way:

          # existingSecret: existing-secret-name
          # secretKeyPassword: key of the password in the secret
          # secretKeyUser: key of the user in the secret

          maxConns: 20
          maxConnLifetime: "1h"
          # tls:
          #  enabled: true
          #  enableHostVerification: true
          #  serverName: _HOST_ # this is strictly required when using serverless CRDB offerings
          #  caFile: /path/to/certs/<CA-file> # Here we assumed that caFile, certFile, keyFile are stored in one secret mounted as 'secret-with-certs' (see: server.additionalVolumes and server.additionalVolumeMounts sections).
          #  certFile: /path/to/certs/<client-cert-file>
          #  keyFile: /path/to/certs/<client-key-file>

      visibility:
        driver: "sql"

        sql:
          driver: "postgres12"
          host: _HOST_
          port: 5432
          database: temporal_visibility
          user: _USER_
          password: _PASSWORD_
          # for a production deployment use this instead of `password` and/or `user`. The secret needs to be provisioned
          # beforehand e.g. with a sealed secret. Keys for the user and the password need to be stored in the same secret.
          # you can specify the secret name and the keys in the following way:

          # existingSecret: existing-secret-name
          # secretKeyPassword: key of the password in the secret
          # secretKeyUser: key of the user in the secret

          maxConns: 20
          maxConnLifetime: "1h"
          # tls:
          #  enabled: true
          #  enableHostVerification: true
          #  serverName: _HOST_ # this is strictly required when using serverless CRDB offerings
          #  caFile: /path/to/certs/<CA-file> # Here we assumed that caFile, certFile, keyFile are stored in one secret mounted as 'secret-with-certs' (see: server.additionalVolumes and server.additionalVolumeMounts sections).
          #  certFile: /path/to/certs/<client-cert-file>
          #  keyFile: /path/to/certs/<client-key-file>

  # additionalVolumes:
  #   - name: secret-with-certs
  #     secret:
  #       secretName: secret-with-certs
  # additionalVolumeMounts:
  #   - name: secret-with-certs
  #     mountPath: /path/to/certs/

admintools:
  enabled: false

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: true

prometheus:
  enabled: false

grafana:
  enabled: false
  
elasticsearch:
  enabled: false

# These values control whether to init and upgrade the schema for the temporal and visibility database
schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true
