name: Build

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  pull_request:
    branches:
      - main

env:
  CR_CONFIGFILE: "${{ github.workspace }}/cr.yaml"
  CR_INDEX_PATH: "${{ github.workspace }}/.cr-index"
  CR_PACKAGE_PATH: "${{ github.workspace }}/.cr-release-packages"
  CR_TOOL_PATH: "${{ github.workspace }}/.cr-tool"
  CHART_PATH: "${{ github.workspace }}/charts/temporal"

jobs:
  build:
    name: Publish Helm Chart in castai/helm-charts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release tag
        if: github.event_name == 'release'
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout helm-charts
        if: ${{ github.event_name == 'release' }}
        # The cr tool only works if the target repository is already checked out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: castai/helm-charts
          path: castai-helm-charts
          token: ${{ secrets.HELM_CHARTS_REPO_TOKEN }}

      - name: Configure Git for helm-charts
        if: ${{ github.event_name == 'release' }}
        run: |
          cd castai-helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        if: ${{ github.event_name == 'release' }}
        uses: azure/setup-helm@v4.1.0
        id: install

      - name: Install CR tool
        if: ${{ github.event_name == 'release' }}
        run: |
          mkdir "${CR_TOOL_PATH}"
          mkdir "${CR_PACKAGE_PATH}"
          mkdir "${CR_INDEX_PATH}"
          curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz"
          tar -xzf cr.tar.gz -C "${CR_TOOL_PATH}"
          rm -f cr.tar.gz

      - name: Bump chart version
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "Release tag is ${{env.RELEASE_TAG}}"
          python ./.github/workflows/bump_chart.py ${CHART_PATH}/Chart.yaml ${{env.RELEASE_TAG}}

      - name: Parse Chart.yaml
        if: ${{ github.event_name == 'release' }}
        id: parse-chart
        run: |
          description=$(yq ".description" < ${CHART_PATH}/Chart.yaml)
          name=$(yq ".name" < ${CHART_PATH}/Chart.yaml)
          version=$(yq ".version" < ${CHART_PATH}/Chart.yaml)
          echo "chartpath=${CHART_PATH}" >> $GITHUB_OUTPUT
          echo "desc=${description}" >> $GITHUB_OUTPUT
          echo "tagname=${name}-${version}" >> $GITHUB_OUTPUT
          echo "packagename=${name}-${version}" >> $GITHUB_OUTPUT
      - name: Create helm package
        if: ${{ github.event_name == 'release' }}
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add incubator https://charts.helm.sh/incubator
          helm repo add elasticsearch https://helm.elastic.co  
          helm repo add grafana https://grafana.github.io/helm-charts
          "${CR_TOOL_PATH}/cr" package "${{ steps.parse-chart.outputs.chartpath }}" --config "${CR_CONFIGFILE}" --package-path "${CR_PACKAGE_PATH}"
          echo "Result of chart package:"
          ls -l "${CR_PACKAGE_PATH}"
          git status

      - name: Make helm charts github release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2.0.4
        with:
          body: |
            ${{ steps.parse-chart.outputs.desc }}
            Source commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          files: |
            ${{ env.CR_PACKAGE_PATH }}/${{ steps.parse-chart.outputs.packagename }}.tgz
            ${{ env.CR_PACKAGE_PATH }}/${{ steps.parse-chart.outputs.packagename }}.tgz.prov
          repository: castai/helm-charts
          tag_name: ${{ steps.parse-chart.outputs.tagname }}
          token: ${{ secrets.HELM_CHARTS_REPO_TOKEN }}

      - name: Update helm repo index.yaml
        if: ${{ github.event_name == 'release' }}
        run: |
          cd castai-helm-charts
          "${CR_TOOL_PATH}/cr" index --config "${CR_CONFIGFILE}" --token "${{ secrets.HELM_CHARTS_REPO_TOKEN }}" --index-path "${CR_INDEX_PATH}" --package-path "${CR_PACKAGE_PATH}" --push

      - name: Commit Chart.yaml changes
        if: ${{ github.event_name == 'release' }}
        run: |
          git status
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add charts/temporal/Chart.yaml
          git stash 
          git fetch
          git checkout main
          git stash pop
          git add charts/temporal/Chart.yaml
          git commit -m "[Release] Update Chart.yaml"
          git push

      - name: Sync chart with helm-charts github
        if: ${{ github.event_name == 'release' }}
        run: |
          cd castai-helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout main
          mkdir -p ./charts/temporal
          cp -r ${CHART_PATH}/* ./charts/temporal
          git add charts/temporal
          git commit -m "Update Temporal chart to ${{env.RELEASE_TAG}}"
          git push